# Generated by Django 3.2.10 on 2022-01-26 23:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='موضوع دسته بندی')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='موضوع تگ')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True, verbose_name='اسلاگ')),
                ('name', models.CharField(max_length=50, verbose_name='نام فروشگاه')),
                ('type', models.CharField(choices=[('SU', 'سوپر مارکت'), ('HY', 'هایپر مارکت'), ('VS', 'فروشگاه سبزیجات'), ('FS', 'میوه فروشی'), ('OS', 'فروشگاه ارگانیک'), ('CS', 'خواربارفروشی')], default='SU', max_length=2, verbose_name='نوع فروشگاه')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='تایید شده است')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='فروشنده')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='اسلاگ')),
                ('name', models.CharField(max_length=50, verbose_name='نام محصول')),
                ('image', models.ImageField(upload_to='productImage/', verbose_name='عکس محصول')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='قیمت محصول')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='درصد تخفیف محصول')),
                ('sales', models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='قیمت محصول')),
                ('stock', models.PositiveIntegerField(blank=True, default=0, verbose_name='تعداد محصول')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='وزن محصول')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به روز شده در')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال است')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='تایید شده است')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='دسته بندی')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_products', to='product.shop', verbose_name='برای فروشگاه')),
                ('tag', models.ManyToManyField(blank=True, to='product.Tag', verbose_name='تگ')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
