# Generated by Django 3.2.10 on 2022-01-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_register',
            field=models.BooleanField(default=False),
        ),
    ]
