# Generated by Django 3.2.10 on 2022-01-26 23:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='قیمت کل')),
                ('total_quantity', models.IntegerField(blank=True, default=0, verbose_name='مقدار کل')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='تخفیف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به روز شده در')),
                ('status', models.CharField(choices=[('CH', 'در حال بررسی'), ('CO', 'تایید شده'), ('CA', 'لغو شد')], default='CH', max_length=9, verbose_name='وضعیت')),
                ('is_payment', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_item_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'unique_together': {('product', 'order')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='order.OrderItem', to='product.Product', verbose_name='محصول'),
        ),
        migrations.AddField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.shop', verbose_name='برای فروشگاه'),
        ),
    ]
